export interface RoomDetails {
  name: string;
  description: string;
  capacity: string;
  beds: string;
  amenities: string[];
  pricePerNight: string;
  highlights: string[];
}

export const roomDatabase: Record<string, RoomDetails> = {
  'Standard Room': {
    name: 'Standard Room',
    description: 'Our welcoming Standard Rooms offer comfortable accommodations with essential amenities for a pleasant stay. Designed for solo travelers and couples.',
    capacity: '2 guests',
    beds: '1 King or 2 Twin beds',
    amenities: [
      'Air conditioning',
      'Premium bedding',
      'En-suite bathroom with premium toiletries',
      'Work desk',
      'Flat-screen TV with cable channels',
      'Free Wi-Fi',
      'Room service',
    ],
    pricePerNight: '₦40,000',
    highlights: [
      'City views available',
      'Modern furnishings',
      'Rain shower',
      'Complimentary minibar essentials',
    ],
  },
  'Executive Room': {
    name: 'Executive Room',
    description: 'Spacious Executive Rooms feature contemporary design with upscale furnishings. Perfect for business travelers and those seeking extra comfort and space.',
    capacity: '2 guests',
    beds: '1 King bed + sofa bed',
    amenities: [
      'Air conditioning',
      'Premium Egyptian cotton bedding',
      'Luxurious bathroom with rainfall shower',
      'Executive workspace with ergonomic seating',
      '42-inch Smart TV',
      'Free high-speed Wi-Fi',
      'Nespresso machine',
      'Complimentary Wi-Fi calling',
      'Executive lounge access',
    ],
    pricePerNight: '₦55,000',
    highlights: [
      'Panoramic city views',
      'Premium toiletries',
      'Evening turndown service',
      'Priority room service',
      'Complimentary pressing service',
    ],
  },
  'Executive Deluxe': {
    name: 'Executive Deluxe',
    description: 'Our Executive Deluxe rooms combine luxury with functionality. Enhanced accommodations featuring premium finishes and elevated hospitality services.',
    capacity: '2 guests',
    beds: '1 King bed + lounge area',
    amenities: [
      'Climate control',
      'Premium Egyptian cotton linens (400+ thread count)',
      'Marble bathroom with separate rain shower and soaking tub',
      'Dual vanities',
      'Full business center',
      'Smart TV with streaming services',
      'Bose sound system',
      'Nespresso machine and mini bar',
      'Executive lounge access with complimentary drinks',
    ],
    pricePerNight: '₦65,000',
    highlights: [
      'Stunning panoramic views',
      'Luxury Bulgari toiletries',
      'Twice-daily maid service',
      'Late checkout at 4 PM',
      'Complimentary airport transfers',
      'Butler service available',
    ],
  },
  'Executive Suite': {
    name: 'Executive Suite',
    description: 'Indulge in the ultimate comfort with our spacious Executive Suites. Featuring a separate living area and premium amenities for discerning guests.',
    capacity: '2 guests',
    beds: '1 King bed + Queen sofa bed in living area',
    amenities: [
      'Climate-controlled bedroom and living room',
      'Premium Egyptian cotton linens',
      'Marble bathroom with rainfall shower, soaking tub, and steam shower',
      'Separate powder room',
      'Full executive office',
      '55-inch Smart TV and entertainment system',
      'Bose surround sound',
      'Premium Nespresso machine',
      'Full minibar with premium selections',
      'Executive lounge access',
    ],
    pricePerNight: '₦90,000',
    highlights: [
      'Spectacular city/garden views',
      'Separate living and sleeping areas',
      'Personalized concierge service',
      'Exclusive lounge access with complimentary beverages',
      'Late checkout at 5 PM',
      'Daily newspaper of choice',
      'Complimentary pressing and laundry service',
    ],
  },
  'Royal Suite': {
    name: 'Royal Suite',
    description: 'Experience regal elegance in our Royal Suites. Designed for the most discerning travelers, featuring opulent furnishings and exclusive services.',
    capacity: '2 guests',
    beds: '1 King bed in bedroom + King sofa bed in living area',
    amenities: [
      'Climate-controlled multi-room layout',
      'Premium Egyptian cotton linens (600+ thread count)',
      'Spa-like marble bathroom with rainfall shower, soaking tub, and private powder room',
      'Heated bathroom floors',
      'Executive office/study with premium technology',
      '65-inch Smart TV in each room',
      'Sound system throughout suite',
      'Premium minibar and wine cooler',
      'Nespresso and cappuccino machines',
      'Exclusive concierge',
    ],
    pricePerNight: '₦100,000',
    highlights: [
      'Exceptional panoramic views',
      'Separate bedroom, living, and work areas',
      'Personal butler service',
      'Access to private lounge with premium bar',
      'Complimentary spa credit (₦20,000)',
      'Free worldwide calls and video conferencing',
      'Chauffeured car service',
      'Personal shopping assistance',
    ],
  },
  'Apartment': {
    name: 'Luxury Apartment',
    description: 'Our Luxury Apartments offer home-like comfort with full amenities. Ideal for extended stays, families, and those seeking a more intimate setting.',
    capacity: '3 guests',
    beds: '2-3 bedrooms with King/Queen beds',
    amenities: [
      'Climate-controlled living spaces',
      'Fully equipped kitchen',
      'Separate living and dining areas',
      'Multiple marble bathrooms',
      'Laundry room with washer/dryer',
      'Multiple entertainment systems',
      'Premium home automation',
      'Full stocked minibar',
      'Nespresso and full coffee bar',
      'Dedicated concierge service',
    ],
    pricePerNight: '₦160,000',
    highlights: [
      'Spacious multi-bedroom layout',
      'Full kitchen facilities',
      'Residential-style furnishings',
      'Private entrance option',
      'Extended checkout at 6 PM',
      'Weekly housekeeping included',
      'Complimentary laundry service',
      'In-apartment dining available',
      'Personal chef available',
    ],
  },
  'Presidential Suite': {
    name: 'Presidential Suite',
    description: 'The pinnacle of luxury and sophistication. Our Presidential Suite offers unparalleled elegance, space, and personalized service for the most distinguished guests.',
    capacity: '3 guests',
    beds: '1 King bed in master suite + multiple additional beds',
    amenities: [
      'Multi-zone climate control',
      'Egyptian cotton linens (1000+ thread count)',
      'Spa-inspired marble bathrooms with rainfall shower, soaking tub, steam room, and sauna',
      'Separate guest powder rooms',
      'Presidential office and meeting area',
      'Private dining room',
      'Library lounge',
      '75-inch Smart TV systems throughout',
      'Premium audio-visual technology',
      'Full wine cellar',
      'Premium minibar',
      'Professional-grade kitchen',
      'Exclusive concierge team',
    ],
    pricePerNight: '₦350,000',
    highlights: [
      'Stunning multi-room suite with separate spaces',
      'Private terrace with lounge seating',
      'Personal butler service 24/7',
      'Executive secretary available',
      'Unlimited spa credit (₦100,000)',
      'Complimentary car service with driver',
      'Michelin-starred chef collaboration available',
      'Private wine tastings',
      'Personalized housekeeping (4x daily)',
      'One-of-a-kind luxury experience',
    ],
  },
};

export function getRoomDetails(roomType: string): RoomDetails | null {
  return roomDatabase[roomType] || null;
}
